version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm run test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - images/*
    - styles/*
    - lerneralex.pdf
    - dist/bundle.js
